### ISSUE TITLE
Add Type Hierarchy motivation?

### ISSUE THREAD

**Issue by marcverhagen** [lapps/org.lappsgrid.vocabulary#3]
I am now adding some motivation of the targets attribute on Spans to the LIF specifications, but maybe a link on vocab.lappsgrid.org that leads to some motivation of the types structure (and to papers on the issue) would be good.

**Comment by ksuderman** [comment]
Do you have any suggestions for such links?  They are easy enough to add.

**Comment by marcverhagen** [comment]
Not yet, I would first need to have some content.

**Comment by ksuderman** [comment]
This issue was moved to lapps/vocabulary-pages#21
