### ISSUE TITLE
Missing type meta property

### ISSUE THREAD

**Issue by marcverhagen** [lapps/org.lappsgrid.vocabulary#4]
We use producer, rules and type in the metadata contains section. The first two are defined as metadata properties on Annotation, but type is not defined.

**Comment by nancyide** [comment]
what is type?On Oct 29, 2015, at 3:44 AM, marcverhagen notifications@github.com wrote:We use producer, rules and type in the metadata contains section. The first two are defined as metadata properties on Annotation, but type is not defined.—Reply to this email directly or view it on GitHub.

**Comment by ksuderman** [comment]
This issue was moved to lapps/vocabulary-pages#22
